name: Release

on:
  push:
    branches:
    - main

jobs:
  release:
    name: Release
    uses: OpenTTD/actions/.github/workflows/rw-entry-release-docker-nomad.yml@v5
    secrets: inherit
    with:
      service: game-coordinator-prod
      url: https://coordinator.openttd.org/
